import Head from 'next/head'
import Layout, { siteTitle } from '../component/Layout'
import utilStyles from "../styles/utils.module.css"
import { getSortedPostsData } from "../lib/posts"
import Link from "next/link"
import Date from "../component/date"

export async function getStaticProps() {
  const allPostData = getSortedPostsData()
  return {
    props: {
      allPostData
    }
  }
}
export default function Home({ allPostData }) {
  console.log(allPostData)
  return (
    <Layout home>
      <Head>
        <title>{siteTitle}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section className={utilStyles.headingMd}>
        <p>(
          This is a simple website - you'll be building a site like this
          )</p>
      </section>
      <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
        <h2 className={utilStyles.headingLg}>
          Blog
        </h2>
        <ul className={utilStyles.list}>
          {allPostData.map(({ id, date, title }) =>
          (
            <li className={utilStyles.listItem} key={id}>
              <Link href={`/posts/${id}`}>
                <a>{title}</a>
              </Link>
              <br />
              <small className={utilStyles.lightText}>
                <Date dateString={date} />
              </small>
            </li>

          )
          )
          }
        </ul>
      </section>
    </Layout>
  )
}
