import Head from 'next/head'
import Image from 'next/image'
import Header from "../Components/Header"
import Nav from "../Components/Nav"
import Results from "../Components/Results"
import requests from "../utils/requests"
export default function Home(props) {


  return (
    <div >
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results requests={props.results} />
    </div>
  )
}


export async function getServerSideProps(context) {
  const genre = context.query.genre
  const request = await fetch(
    `https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`
  ).then(response => response.json())
  return {
    props: {
      results: request.results
    }
  }
}